import { GetServerSideProps, InferGetServerSidePropsType } from "next";
import Head from "next/head";
import styles from "../../styles/Home.module.css";
import { useEffect, useState } from "react";
import usePriceOracleTime, {
  NETWORKS,
  NetworkType,
  timeConverter,
} from "../hooks/usePriceOracleTime";
import { useRouter } from "next/router";
import { LayoutContainer, Main, Title } from "../components/Layout";
import MenuNetwork from "../components/MenuNetwork";

export default function Home() {
  const router = useRouter();
  const { network } = router.query;

  const {
    checkOracle,
    dateTimeCountdown,
    timeUntil,
    canConsult,
    isLoading,
    currentNetwork,
  } = usePriceOracleTime();

  useEffect(() => {
    checkOracle(network as NetworkType);
  }, [checkOracle]);

  return (
    <LayoutContainer>
      <Head>
        <title>Price Oracle Health Status</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Title>Price Oracle Health Status</Title>
      <MenuNetwork />
      <Main>
        {isLoading ? (
          <h3>Loading...</h3>
        ) : (
          <>
            <>
              <h3>Network:</h3>
              <div>{currentNetwork}</div>
              <h3>Can Consult Prices:</h3>
              <div>{canConsult ? "Yes" : "No"}</div>
            </>
            {dateTimeCountdown > 0 && (
              <>
                <h3>Need wait until:</h3>
                <div>{timeConverter(dateTimeCountdown)}</div>
                <h3>When:</h3>
                <div>{timeUntil}</div>
              </>
            )}
          </>
        )}
      </Main>
    </LayoutContainer>
  );
}
