import React from "react";
import styled from "styled-components";

export const LayoutContainer = styled.div`
  min-height: 100vh;
  padding: 0 0.5rem;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  height: 100vh;
`;

export const Main = styled.main`
  padding: 0;
  flex: 1;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
`;

export const Title = styled.div`
  a {
    color: #0070f3;
    text-decoration: none;
  }

  a:hover,
  a:focus,
  a:active {
    text-decoration: underline;
  }

  margin: 0;
  line-height: 1.15;
  font-size: 3rem;

  .description {
    text-align: center;
  }
`;

// export default function Layout() {
//   return (
//     <LayoutContainer>
//       <Head>
//         <title>Price Oracle Health Status</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <h1 className={styles.title}>Price Oracle Health Status</h1>
//       <MenuNetwork></MenuNetwork>
//       <main className={styles.main}>
//         {isLoading ? (
//           <h3>Loading...</h3>
//         ) : (
//           <>
//             <>
//               <h3>Network:</h3>
//               <div>{currentNetwork}</div>
//               <h3>Can Consult Prices:</h3>
//               <div>{canConsult ? "Yes" : "No"}</div>
//             </>
//             {dateTimeCountdown > 0 && (
//               <>
//                 <h3>Need wait until:</h3>
//                 <div>{timeConverter(dateTimeCountdown)}</div>
//                 <h3>When:</h3>
//                 <div>{timeUntil}</div>
//               </>
//             )}
//           </>
//         )}
//       </main>
//     </LayoutContainer>
//   );
// }
